Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,11 +23,11 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
-      - name: Verify Important Component Exists
-        run: |
-          echo "Checking if required component exists..."
-          test -f src/Dashboards/AdminDashboard/PurchaseScreen/AdminPurchaseHome.jsx || \
-          (echo "ERROR: File not found: src/Dashboards/AdminDashboard/PurchaseScreen/AdminPurchaseHome.jsx" && exit 1)
+      #- name: Verify Important Component Exists
+       # run: |
+        #  echo "Checking if required component exists..."
+         # test -f src/Dashboards/AdminDashboard/PurchaseScreen/AdminPurchaseHome.jsx || \
+         # (echo "ERROR: File not found: src/Dashboards/AdminDashboard/PurchaseScreen/AdminPurchaseHome.jsx" && exit 1)
 
       - name: Build Application
         run: npm run build
